README.md
ell-studio/package-lock.json
ell-studio/package.json

`pip install .` was breaking because `react-scripts` was not in `package.json`, added the dependency explicitly, and updated the README since it is referencing a non-existant `npm run` target

add missing dependency, update README

---

requirements.txt

Requests needed to run `ollama`
```
Traceback (most recent call last):
File "$HOME/projects/ell-fork/examples/hello_world.py", line 1, in <module>
import ell
File "$HOME/projects/ell-fork/src/ell/__init__.py", line 5, in <module>
import ell.models
File "$HOME/projects/ell-fork/src/ell/models/__init__.py", line 2, in <module>
import ell.models.ollama
File "$HOME/projects/ell-fork/src/ell/models/ollama.py", line 3, in <module>
import requests
ModuleNotFoundError: No module named 'requests'
```
added to `requirements.txt` issue resolved.

add missing dependency requests

---

src/ell/providers/openai.py
src/ell/types/message.py

`image_detail` param within OpenAI's API is not handled within the `api_params` of the ell decorators. This PR fixes that by adding `image_detail` to the `ContentBlock` object to give a developer more granular control of their image quality rather than associating it at the top level via the decorator.
Consider the following Message:
```
ell.Message(role="user", content=["You are a helpful assistant that takes in images and returns a description of the image.",
ell.ContentBlock(image=x, image_detail="low"), ell.ContentBlock(image=x, image_detail="high"), ell.ContentBlock(image=x)])
```
Linked here on [Discord](https://discord.com/channels/1266849047314960394/1266849239913463998/1284220273758965760)
Stemming from this [issue](https://discord.com/channels/1266849047314960394/1266849239913463 …

Enable image_detail on ContentBlock for OpenAI

---

docs/src/getting_started.rst

I believe the second "system prompt" in this sentence is supposed to be "docstring".

[Docs] Correct getting started typo

---

src/ell/providers/openai.py

This PR resolves a Pydantic value error exception that can occur when the streamed response from an OpenAI-like service does not produce a `role` in the initial chunk. A default role of `assistant` is used when a role is not found. The message composition now uses this `role` if the call result is flagged as `actual_streaming`.
- [Issue 175](https://github.com/MadcowD/ell/issues/175)
- updates OpenAI `process_response` to extract `role` with default

Resolve unknown message role exceptions

---

docs/src/installation.rst
poetry.lock
pyproject.toml

Currently, the install of `ell-ai` via pip does not include the Anthropic SDK as a dependency which prevents auto-registration of the `claude` series of models and providers in bare python environments.
This PR adds an `anthropic` extra (installable via `pip install ell-ai[anthropic]`), permitting simple one-shot installation and updates the docs accordingly. It also adds an explicit `openai` extra (default case) as well as an `all` extra for installing all of the above (including future client SDKs).

Add "anthropic" pip install extra.

---

docs/src/installation.rst

Fixes anthropic installation command being rendered as a quote block:

Fix syntax error in installation.rst

---

poetry.lock
pyproject.toml

Repairs a sub-dependency inclusion regression introduced in #199 due to unexpected `poetry` behavior.
Before (`openai` is only conditionally installed when the "openai" or "all" extra is specified):
```
om:ell kw$ git rev-parse HEAD
585b695a948d228f476c2facfb87a8950af98358
om:ell kw$ uvx poetry build
Building ell-ai (0.0.10)
- Building sdist
- Built ell_ai-0.0.10.tar.gz
- Building wheel
- Built ell_ai-0.0.10-py3-none-any.whl
om:ell kw$ unzip -p ./dist/ell_ai-0.0.10-py3-none-any.whl ell_ai-0.0.10.dist-info/METADATA | grep openai
Provides-Extra: openai
Requires-Dist: openai (>=1.47.0,<2.0.0) ; extra == "openai" or extra == "all"
om:ell kw$
```
After (`openai` is always installed):
```
om:ell kw$ uvx poetry build
Building ell-ai (0.0.10)
- Building sdist
- Built ell_ai-0.0.10.tar.gz
- …
```

Repair openai dependency inclusion regression.

---

README.md

```
pip install -U ell-ai[all]
```
on `zsh` you get an error, this results in:
```
zsh: no matches found: ell-ai[all]  
```
This resolves it:
```
pip install -U "ell-ai[all]"
```
Should we change this or leave it alone? The former worked on bash.

fix install command in readme?

---

src/ell/types/message.py

other packages using ell, that are also using mypy for type checking need to know that ell is strongly typed.

add py.typed to ell package

---

src/ell/studio/__main__.py

**Issue**
Currently, running `ell-studio` with no args fails unexpectedly with an unhandled `TypeError`:
```
om:ell kw$ uvx --from ell-ai[all] ell-studio
Traceback (most recent call last):
File "/Users/kw/.cache/uv/archive-v0/yRhKWbo2kdkMVmJ2BWBWg/bin/ell-studio", line 10, in <module>
sys.exit(main())
^^^^^^
File "/Users/kw/.cache/uv/archive-v0/yRhKWbo2kdkMVmJ2BWBWg/lib/python3.12/site-packages/ell/studio/__main__.py", line 44, in main
db_path = os.path.join(args.storage_dir)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen posixpath>", line 76, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType
om:ell kw$
```
**Changes**
* Fix the default behavior (no args passed) to align with the documented default of cwd (via `ell.studio.config.Config`).
* Port usage of `os.path` …

Improve ell-studio CLI UX.

---

pyproject.toml

I think its fine with numpy > 1.26.

add support for numpy version < 2.0

---

ell-studio/src/pages/Home.js

Previously, you had to click on the 'title' to be renavigated. This PR Updates it so that the entire card is the click area.

[ell-studio] Update Home Page Card Click Area

---

src/ell/configurator.py
src/ell/util/differ.py
tests/test_autocommit_model.py

I don't use OpenAI stuff really so I wanted Claude 3 Haiku to write my autocommits.
Main changes:
- config param for autocommit_model
- fixed diff in `write_commit_message_for_diff`
- the diff variable was a generator, so you'd get this for the value of diff in a fstring: `<generator object unified_diff at 0x10aef4d40>`
- fixed by joining lines of diff with newline
- `write_commit_message_for_diff` max tokens 500
- should be a reasonable limit, just needed to set this because of the Anthropic client requirement
- changed `write_commit_message_for_diff` prompt, got more consistent behavior out of Claude 3 Haiku this way
- I just followed some of Anthropic's guidelines. GPT 4o mini didn't change its behavior much, you can check the difference for two tests in …

Feature: configure autocommit model

---

__testing__.py
ell-studio/src/components/source/DiffRenderer.js
ell-studio/src/components/source/LMPSourceView.js
src/ell/studio/__main__.py
src/ell/util/closure.py
src/ell/util/differ.py

Fix for #287 
* culprit is Black formatter adds space after # comment
* it doesn't always though because if the formatter raises exception, no format
* fixed by chaning `#<BV>` => `# <BV>` but for all tags
NOTE: this might not be the right way since without rerunning all the LMPs, the old source persists in the DB, so the old #<BV> tags won't get rendered right in the React app. Could instead enforce that # <BV> becomes #<BV> even after formatting, or strip out the delimiter before formatting and add it back in after.

Got <BV> to stop showing up in LMP deps

---

src/ell/models/ollama.py
src/ell/util/_warnings.py

* OpenAI API requires there be a `api_key` field although Ollama's API doesn't require it
* Fixed `_autocommit_warning` to warn when there's no client for config.autocommit_model instead of hardcoded "gpt-4o-mini" string and updated warning message accordingly
#310

Fix issue #310 but also autocommit when no OpenAI key present

---

src/ell/providers/openai.py

Message(role=role,
content=_lstr(content=text,origin_trace=origin_id)))
sometimes role is empty and will throw exception:
```
pydantic_core._pydantic_core.ValidationError: 1 validation error for Message
role
Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
For further information visit https://errors.pydantic.dev/2.9/v/string_type
python-BaseException
```

role=role or "assistant"

---

src/ell/providers/bedrock.py

For non streaming responses, Bedrock usage metadata was not being captured. Updated the metadata `dict` in line with how it was being handled for streaming responses.

Bedrock usage metadata

---

src/ell/__init__.py
src/ell/lmp/__init__.py
src/ell/models/__init__.py
src/ell/providers/__init__.py
src/ell/types/__init__.py
src/ell/util/__init__.py

Update all `__init__.py`s to include an `__all__` definition. Fixes `reportPrivateImportUsage` pylance linting error. Also removed * imports to lessen namespace cluttering.

Add `__all__` to `__init__.py`s

---

src/ell/types/message.py
tests/test_message_type.py

#336 
Fix to "Round-trip Message Serialization/Deserialization"
The test failed before, now it passes. The other tests still pass. It should work on 'image', 'audio', 'tool_call', 'parsed', 'tool_result', but I haven't tested it. Do you think I should still do that?

Fix Round trip Message serialization/deserialization

---

ell-studio/src/components/invocations/details/InvocationDetailsPopover.js
ell-studio/src/components/source/CodeSection.js

This PR updates CodeSection so the user can collapse the displayed code by clicking anywhere within the component. Previously you can only collapse code by clicking on the header, which means you have to scroll all the way up to header if your result text is long. 
It also fixes the issue of the invocation panes overlapping on certain screen sizes (see below) by wrapping each pane in a ScrollArea.

[ell-studio] Update CodeSection clickable area and fix overlapping Invocation Panes

---

src/ell/providers/groq.py

Fixes #289 
* Groq assistant turns can only have `content: <str>`, no arrays or multimodal
* Warning that Groq cannot handle response_format argument: This is because the way that its passed, I'm working on a separate commit for that.

Fix multiturn conversation error Groq

---

pyproject.toml

Previous caret version requirement `^0.0.21` for sqlmodel only allows version ">=0.0.21, <0.0.22" and seems too strict. Changing to `>=0.0.21, <0.1.0` to allow newer versions.
Ref to Poetry documentation: [Caret requirements - Dependency specification](https://python-poetry.org/docs/dependency-specification/#caret-requirements)
> 0.0.x is not considered compatible with any other version.

fix: version requirement too strict for `sqlmodel`

---

examples/wikipedia_mini_rag.py

* Introduced `wikipedia_mini_rag.py` to showcase integration of LLM agents with Wikipedia using `lynx`.
* Key functionalities:
* `search_wikipedia`: tool to return search results and links.
* `wikipedia_page_content`: fetches page content.
* `search_wikipedia_and_suggest_page_to_read`: AI suggests Wikipedia page based on query.
* `answer_query_by_reading_wikipedia_page`: AI reads page content to answer queries.
* Implements verbosity via command-line flags `-v` and `-vv`.
* Example positioned in `examples/` to guide educational purposes.
* Integrates LLM workflows using `ell` library, illustrating refined AI-agent interactions with tools.
Additionally gives users educational task (and link to solution if someone seeking spoilers).

examples += `wikipedia_mini_rag.py` for educational LLM+Wikipedia integration

---

examples/llm_lottery.py

* Introduce `llm_lottery.py`, a new example script leveraging LLM with predefined tools.
* Tools introduced:
* `buy_lottery_ticket`: Purchases a lottery ticket.
* `check_lottery_result`: Validates if purchased ticket wins.
* Implements `play_lottery`, enhancing LLM actions with GPT-4o-mini model.
* Included `loop_llm_and_tools` for iterative task resolution until completion.
* Integrated `argparse` for verbosity, showcasing scalable CLI with `-v`, `-vv` flags.
* Establishes script execution with `main()` for elucidated tool dynamics.
* Illustrates LLM capabilities in procedural, educational lottery gameplay context.

feat(examples): add `llm_lottery.py` for demonstrating LLM tool integration

---

src/ell/util/closure.py

Don't know if this creates any other issues but the problem seemed to be that by default, getsource is looking for the source filename which in jupyter doesn't exist.

fix getsource for jupyter context

---

src/ell/models/__init__.py
src/ell/models/google.py

This change uses Google's OpenAI compatible API endpoint and adds google gemini models to the ell framework.

Register Google Gemini Models

---

ell-studio/src/pages/Evaluations.js

Removed `n_evals=10,`
Made input into a list `    dataset=[{"input": ["Hello"], "expected": "Hi there!"}],`

fix: Corrected Evaluation Example

---

docs/src/installation.rst
src/ell/configurator.py
src/ell/stores/__init__.py
src/ell/studio/__init__.py

Adding quotes to the installation script makes it compatible with zsh shells, while still working with any other shell. Example: `pip install -U "ell-ai[all]"`. Basically the problem is that the square brackets have special meaning in ZSH as they're used for pattern matching, so the shell is trying to interpret `[all]` as a pattern rather than passing it literally to pip.

fix: update install scripts to use quotes for zsh compatibility

---

src/ell/providers/anthropic.py

Fix the issue that causes the prompt_tokens in the metadata to become 0 when using Claude Sonnet.

[bug fix] prompt_tokens is 0 when using sonnet
